## Aula 13/12/2025

### Biblioteca Numpy 🧮

Utilização: Sempre que precisarmos trabalhar com aplicações matemáticas ou científicas.

**Áreas de aplicação:**
- Análise de Dados
- Machine Learning
- Matemática no geral

**Características**
- Base forte em vetores de n dimensões
- Inúmeras funções matemáticas 
- Boa integração com várias outras bibliotecas famosas

**Vantagens**
- Ótima documentação
- Comunidade ativa
- Fácil de utilizar
- Já incluso no pacote anaconda
- Integração com Matplotlib
- Integração com Seaborn
- Integração com Pandas
- Integração com Scikit-learn
- Integração com Statsmodel

<a href="https://numpy.org/doc/stable/">Biblioteca Numpy</a>

In [11]:
import numpy as np

numeros = [1, 2, 3, 4, 5]

arr = np.array(numeros)
print(arr)
print(type(arr))
print()

# Atributos
print('Tipos de dados do array:', arr.dtype)
print('N de dimensões do array:', arr.ndim)
print('Shape ou ordem array:', arr.shape)
print('Quantidade de elementos no array:', arr.size)

[1 2 3 4 5]
<class 'numpy.ndarray'>

Tipos de dados do array: int32
N de dimensões do array: 1
Shape ou ordem array: (5,)
Quantidade de elementos no array: 5


### Arrays x Listas

In [26]:
print(numeros)
print(arr)
print()

# Soma
print(numeros + numeros)
print(arr + arr)
print()

# Produto
print(numeros * 5)
print(arr * 5)

# Divisão
try:
    print(numeros / 2)
except TypeError:
    print('Não podemos dividir uma lista por um número')
finally:    
    print(arr / 2)

[1, 2, 3, 4, 5]
[1 2 3 4 5]

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]
Não podemos dividir uma lista por um número
[0.5 1.  1.5 2.  2.5]


### Funções aplicadas a vetores

In [57]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Atributos
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print()

# Operações
print(arr + 5)
print(arr * 3)
print(arr / 2)
print(arr ** 2)

# Funções
print(np.exp(arr).round(3))
print(np.sin(arr * np.pi / 180).round(3))
print(np.cos(arr * np.pi / 180).round(3))
print(np.tan(arr * np.pi / 180).round(3))
print(np.log(arr).round(3))

int32
(10,)
1
10

[ 6  7  8  9 10 11 12 13 14 15]
[ 3  6  9 12 15 18 21 24 27 30]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
[  1   4   9  16  25  36  49  64  81 100]
[2.7180000e+00 7.3890000e+00 2.0086000e+01 5.4598000e+01 1.4841300e+02
 4.0342900e+02 1.0966330e+03 2.9809580e+03 8.1030840e+03 2.2026466e+04]
[0.017 0.035 0.052 0.07  0.087 0.105 0.122 0.139 0.156 0.174]
[1.    0.999 0.999 0.998 0.996 0.995 0.993 0.99  0.988 0.985]
[0.017 0.035 0.052 0.07  0.087 0.105 0.123 0.141 0.158 0.176]
[0.    0.693 1.099 1.386 1.609 1.792 1.946 2.079 2.197 2.303]


### Matrizes

In [94]:
import numpy as np

matriz_1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [4, 4, -5]
])

matriz_2 = np.array([
    [5, 6, 10],
    [7, 7, 2],
    [5, -2, 3]
])

print(matriz)
print(type(matriz))

print(matriz.dtype)
print(matriz.shape)
print(matriz.size)
print(matriz.ndim)

# Operações entre matrizes

# Soma
print(matriz_1 + matriz_2)
print()

# Subtração
print(matriz_1 - matriz_2)
print()

# Multiplicação (item a item)
print(matriz_1 * matriz_2)
print()

# Divisão 
print((matriz_1 / matriz_2).round(2))
print()

# Multiplicação de Matrizes
# 3x3 3x3
print(np.matmul(matriz_2, matriz_1))
print(matriz_2 @ matriz_1)
print(np.dot(matriz_1, matriz_2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int32
(2, 3)
6
2
[[ 6  8 13]
 [11 12  8]
 [ 9  2 -2]]

[[-4 -4 -7]
 [-3 -2  4]
 [-1  6 -8]]

[[  5  12  30]
 [ 28  35  12]
 [ 20  -8 -15]]

[[ 0.2   0.33  0.3 ]
 [ 0.57  0.71  3.  ]
 [ 0.8  -2.   -1.67]]

[[ 69  80   1]
 [ 43  57  53]
 [  9  12 -12]]
[[ 69  80   1]
 [ 43  57  53]
 [  9  12 -12]]
[[34 14 23]
 [85 47 68]
 [23 62 33]]


### Outras formas de criar arrays

In [109]:
import numpy as np

# arange

a = np.arange(1, 51, 2)
print(a)
print(type(a))

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

# linspace

b = np.linspace(0, 100, 5)
print(b)
print(type(b))

print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
<class 'numpy.ndarray'>
1
(25,)
25
int32
[  0.  25.  50.  75. 100.]
<class 'numpy.ndarray'>


### Random

In [367]:
import numpy as np

np.random.seed(1)

# Gerando um único valor aleatório
valor = np.random.rand() * 100
print(valor)

valor_2 = np.random.randint(1, 1000)
print(valor_2)

# Gerando arrays aleatórios
arr_1 = (np.random.rand(1, 10) * 100).round(2)
print(arr_1)

arr_2 = (np.random.rand(2, 3) * 100).round(2)
print(arr_2)
print(arr_2.shape)

arr_3 = np.random.randint(1, 1000, 30)
print(arr_3)



41.7022004702574
909
[[93.26 12.81 99.9  23.61 39.66 38.79 66.97 93.55 84.63 31.33]]
[[52.45 44.35 22.96]
 [53.44 91.4  45.72]]
(2, 3)
[754 504 479 865  87 142 394   8 320 830 535 314 514 897 317 210 265 729
 654 628 432 634 457 543  72 388 455 918 562 314]


TypeError: randint() got an unexpected keyword argument 'shape'